const CALC_VERSION = '1.0.0';
const HOURLY_COST = 25;
const SHOWINGS_PER_VACANCY = 5;
const VACANCY_REDUCTION = 0.5;
const TIME_REDUCTION = 0.7;
const CURRENCY = 'USD';

module.exports = {
  CALC_VERSION,
  HOURLY_COST,
  SHOWINGS_PER_VACANCY,
  VACANCY_REDUCTION,
  TIME_REDUCTION,
  CURRENCY
};
